force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <description>Stores country information from CountryLayer.com API. Refreshed once a day at midnight.</description>
    <label>Country</label>
    <nameField>
        <displayFormat>C-{000}</displayFormat>
        <label>Country Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Country__c/fields/Alpha2Code__c.field-meta.xml
<CustomField>
    <fullName>Alpha2Code__c</fullName>
    <label>Alpha2Code</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/Alpha3Code__c.field-meta.xml
<CustomField>
    <fullName>Alpha3Code__c</fullName>
    <label>Alpha3Code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/CapitalCity__c.field-meta.xml
<CustomField>
    <fullName>CapitalCity__c</fullName>
    <label>Capital City</label>
    <length>160</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <length>160</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/CountryAlpha2Code__c.field-meta.xml
<CustomField>
    <fullName>CountryAlpha2Code__c</fullName>
    <description>Alpha2Code for the Country set in the Address field.</description>
    <label>Country Alpha2Code</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/CountryAlpha3Code__c.field-meta.xml
<CustomField>
    <fullName>CountryAlpha3Code__c</fullName>
    <description>Alpha3Code of the country set in the Address field, populated from the CountryLayer API.</description>
    <label>Country Alpha3Code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/CountryCapital__c.field-meta.xml
<CustomField>
    <fullName>CountryCapital__c</fullName>
    <description>Capital of the country set in the Address field, populated from the CountryLayer API.</description>
    <label>Country Capital</label>
    <length>160</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/CountryRegion__c.field-meta.xml
<CustomField>
    <fullName>CountryRegion__c</fullName>
    <description>Region of the country set in the Address field, populated from the CountryLayer API.</description>
    <label>CountryRegion</label>
    <length>160</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LeadTriggerHandler.cls
public with sharing class LeadTriggerHandler {
    
    /**
     * Before insert trigger handler
     * @param newLeads List of new Leads records before save
     */
    public static void beforeInsert(List<Lead> newLeads) {
        if(canQueryCountries()) {
            List<String> countryNames = new List<String>();
            List<Lead> leadsToUpdate = new List<Lead>();

            for(Lead ld : newLeads) {
                if(!String.isBlank(ld.Country)) {
                    leadsToUpdate.add(ld);
                    countryNames.add(ld.Country);
                }
            }

            Map<String, Country__c> countriesByName = CountryLayerService.getCountriesByName();
            updateLeadsWithCountries(leadsToUpdate, countriesByName);
        }
    }

    /**
     * Before update trigger handler
     * @param newLeads List of newly updated Leads records before save
     * @param oldLeadMap Map with old versions of newly updated Lead records, by ID
     */
    public static void beforeUpdate(List<Lead> newLeads, Map<Id, Lead> oldLeadMap) {
        if(canQueryCountries()) {
            List<String> countryNames = new List<String>();
            List<Lead> leadsToUpdate = new List<Lead>();

            for(Lead ld : newLeads) {
                if(ld.Country != oldLeadMap.get(ld.Id).Country) {
                    leadsToUpdate.add(ld);
                    countryNames.add(ld.Country);
                }
            }

            Map<String, Country__c> countriesByName = CountryLayerService.getCountriesByName();
            updateLeadsWithCountries(leadsToUpdate, countriesByName);
        }
    }

    /**
     * Checks if the current user has permission to query Country__c
     * @return Has/doesn't have permission
     */
    @TestVisible
    private static Boolean canQueryCountries() {
        return SObjectType.Country__c.fields.CapitalCity__c.isAccessible() &&
            SObjectType.Country__c.fields.Region__c.isAccessible() &&
            SObjectType.Country__c.fields.Alpha2Code__c.isAccessible() &&
            SObjectType.Country__c.fields.Alpha3Code__c.isAccessible();
    }

    /**
     * Updates Lead records with country info from the Country__c record
     * matching the Address Country
     * @param leads List of Lead records to update
     * @param countriesByName Map of Country__c records by Name__c
     */
    @TestVisible
    private static void updateLeadsWithCountries(List<Lead> leads, Map<String, Country__c> countriesByName) {
        for(Lead ld : leads) {
            Country__c country = countriesByName.get(ld.Country);
            ld.CountryCapital__c = country != null ? country.CapitalCity__c : null;
            ld.CountryRegion__c = country != null ? country.Region__c : null;
            ld.CountryAlpha2Code__c = country != null ? country.Alpha2Code__c : null;
            ld.CountryAlpha3Code__c = country != null ? country.Alpha3Code__c : null;
        }
    }
}