force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <description>Stores country information from CountryLayer.com API. Refreshed once a day at midnight.</description>
    <label>Country</label>
    <nameField>
        <displayFormat>C-{000}</displayFormat>
        <label>Country Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Country__c/fields/Alpha2Code__c.field-meta.xml
<CustomField>
    <fullName>Alpha2Code__c</fullName>
    <label>Alpha2Code</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/Alpha3Code__c.field-meta.xml
<CustomField>
    <fullName>Alpha3Code__c</fullName>
    <label>Alpha3Code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/CapitalCity__c.field-meta.xml
<CustomField>
    <fullName>CapitalCity__c</fullName>
    <label>Capital City</label>
    <length>160</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <length>160</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GeneralSettings__c/GeneralSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>General Settings</label>
</CustomObject>

force-app/main/default/objects/Lead/fields/CountryAlpha2Code__c.field-meta.xml
<CustomField>
    <fullName>CountryAlpha2Code__c</fullName>
    <description>Alpha2Code for the Country set in the Address field.</description>
    <label>Country Alpha2Code</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/CountryAlpha3Code__c.field-meta.xml
<CustomField>
    <fullName>CountryAlpha3Code__c</fullName>
    <description>Alpha3Code of the country set in the Address field, populated from the CountryLayer API.</description>
    <label>Country Alpha3Code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/CountryCapital__c.field-meta.xml
<CustomField>
    <fullName>CountryCapital__c</fullName>
    <description>Capital of the country set in the Address field, populated from the CountryLayer API.</description>
    <label>Country Capital</label>
    <length>160</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/CountryRegion__c.field-meta.xml
<CustomField>
    <fullName>CountryRegion__c</fullName>
    <description>Region of the country set in the Address field, populated from the CountryLayer API.</description>
    <label>CountryRegion</label>
    <length>160</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LeadTriggerHandlerTest.cls
@isTest
private class LeadTriggerHandlerTest {
    
    /**
     * Checks the Lead records are updated from Country__c records
     */
    @isTest
    private static void updateLeadsWithCountries() {
        GeneralSettings__c settings = TestData.insertGeneralSettings(); // disable automation
        Map<String, Country__c> testCountries = TestData.createCountryRecordsByNameMap(2);
        List<Lead> testLeads = TestData.createLeadRecords(2, testCountries.values()[0].Name__c);
        testLeads.addAll(TestData.createLeadRecords(2, testCountries.values()[1].Name__c));
        testLeads.addAll(TestData.createLeadRecords(2, null));

        Test.startTest();
        LeadTriggerHandler.updateLeadsWithCountries(testLeads, testCountries);
        Test.stopTest();

        System.assertEquals(
            testCountries.values()[0].CapitalCity__c,
            testLeads[0].CountryCapital__c,
            'Capital is not correct on Lead'
        );
        System.assertEquals(
            testCountries.values()[0].Region__c,
            testLeads[1].CountryRegion__c,
            'Region is not correct on Lead'
        );
        System.assertEquals(
            testCountries.values()[1].Alpha2Code__c,
            testLeads[2].CountryAlpha2code__c,
            'Alpha2Code is not correct on Lead'
        );
        System.assertEquals(
            testCountries.values()[1].Alpha3Code__c,
            testLeads[3].CountryAlpha3code__c,
            'Alpha3Code is not correct on Lead'
        );
        System.assertEquals(null, testLeads[4].CountryCapital__c, 'Capital is not null');
        System.assertEquals(null, testLeads[5].CountryAlpha3code__c, 'Alpha3Code is not null');
    }

}